# Generated by Django 4.2.21 on 2025-05-14 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='recurrence_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meeting.booking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='recurrence_rule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
