# Generated by Django 4.2.21 on 2025-05-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_booking_recurrence_group_booking_recurrence_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='recurrence_group',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
