# Generated by Django 4.2.21 on 2025-05-16 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_alter_booking_recurrence_group'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('name', 'location')},
        ),
    ]
