# Generated by Django 4.2.21 on 2025-05-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0005_alter_room_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='resources',
            field=models.CharField(max_length=255),
        ),
    ]
